version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - TELEGRAM_BOT_TOKEN
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama
      - chromadb

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
    ports:
      - "8000:8000"

volumes:
  ollama_data:
  chroma_data:
